FROM quay.io/jupyter/scipy-notebook:latest
# The image index can be found here:
# https://hub.docker.com/r/jupyter/scipy-notebook/tags/

# Begin custom install scripts:

# Escalate privileges to run apt-get
USER root
RUN apt-get update && apt-get -y install apt-utils
RUN apt-get -y install vim-tiny curl less wget
RUN ln -s /usr/bin/vim.tiny /usr/local/bin/vim

# De-escalate
USER $NB_UID

# Required libraries for 141

# Required for cs1-libraries
RUN pip install --no-cache-dir ipycanvas
RUN pip install --no-cache-dir ipyevents
RUN pip install --no-cache-dir jupyter-ui-poll
RUN pip install --no-cache-dir nbgitpuller

RUN pip install --no-cache-dir okpy

# okpy pins an old urllib3; we need to upgrade for the Docker image to run.
RUN pip install --no-cache-dir urllib3 --upgrade

# Install RISE for slideshows
RUN pip install --no-cache-dir RISE

# Install COMP141 libraries
RUN pip install --no-cache-dir git+https://github.com/Rhodes-CS-Department/comp141-libraries.git

# Additional Extensions
RUN pip install --no-cache-dir jupyterlab_code_formatter
RUN pip install --no-cache-dir black isort
RUN pip install --no-cache-dir lckr-jupyterlab-variableinspector
RUN pip install --no-cache-dir jupyterlab-limit-output
RUN pip install --no-cache-dir jupyterlab-spellchecker
