FROM jupyter/scipy-notebook:latest
# The image index can be found here:
# https://hub.docker.com/r/jupyter/scipy-notebook/tags/

# Begin custom install scripts:
RUN pip install --no-cache-dir ipycanvas
RUN pip install --no-cache-dir nbgitpuller
RUN pip install --no-cache-dir okpy
