kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jupyterhub-user-pd
provisioner: pd.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  type: pd-standard

